services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: enerbit
      POSTGRES_DB: enerbit
      POSTGRES_USER: enerbit
    volumes:
      - db:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  backend:
    depends_on:
      - db
      - cache
    container_name: enerbit
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000:8000"
    volumes:
      - "./enerbit:/app/enerbit"
      - "./requirements.txt:/app/requirements.txt"
    environment:
      DEBUG: true
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: enerbit
      DB_PASSWORD: enerbit
      DB_NAME: enerbit
      REDIS_HOST: cache
      REDIS_PORT: 6380
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    links:
      - db
      - cache

volumes:
  cache:
    driver: local
  db:
    driver: local
