from .servicies.serializers_services import WorkOrderSerializerList,WorkOrderSerializer,WorkOrderSerializerUpdate
from .customers.serializers_customers import CustomerSerializerList,CustomerSerializerUpdate,CustomerSerializer
from ..models.models import *
