# Generated by Django 4.2.6 on 2023-10-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('NW', 'New'), ('DN', 'Done'), ('CD', 'Cancelled')], default='NW', max_length=255),
        ),
    ]
