# Generated by Django 4.2.6 on 2023-10-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_workorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=255),
        ),
    ]
