# Generated by Django 4.2.6 on 2023-10-24 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_workorder_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
